   { handleDrawColor, "DRAWCOLOR", "( r g b -- ) Sets the drawing colour to RGB." },
   { handleDrawPixel, "DRAWPIXEL", "( x y -- ) Draws a pixel at x:y." },
   { handleDrawLine, "DRAWLINE", "( x0 y0 x1 y1 -- ) Draws a line between x0,y0 and x1, y1." },
   { handleFillRect, "FILLRECT", "( x y w h -- ) Draws a square of width w and height h at x,y." },
   { handleDrawRect, "DRAWRECT", "( x y w h -- ) Fills a square of width w and height h at x,y." },
   { handleCLS, "CLS", "( r g b -- ) Clears the screen with colour RGB." },
   { handleDRAWSTRING, ".DT\"", "( x y --) Draws the next string at x:y." },
   { handleDRAWSTACKSTRING, ".DST", "( x y s --) Draws string s at x:y." },
   { handleFONT, "FONT", "( s -- ) Sets current font to file." },
   { handleRefresh, "REFRESH", "( -- ) Refreshes screen." },
   { handleWIDTH, "WIDTH", "( -- w ) Puts screen width on stack." },
   { handleHEIGHT, "HEIGHT", "( -- h ) Puts screen height on stack." },
