  { handleDrawColor, "DRAWCOLOR" },
  { handleDrawPixel, "DRAWPIXEL" },
  { handleDrawLine, "DRAWLINE" },
  { handleFillRect, "FILLRECT" },
  { handleDrawRect, "DRAWRECT" },
  { handleCLS, "CLS" },
  { handleDRAWSTRING, ".DT\"" },
  { handleFONT, "FONT" },
