  { handleCLS, "CLS" },
  { handleGetWidth, "WIDTH" },
  { handleGetHeight, "HEIGHT" },
  { handleDrawline, "DRAWLINE" },
  { handleSetColor, "SETCOLOR" },
  { handleDisplay, "DISPLAY" },
  { handleDelay, "DELAY" },
  { handleDrawPixel, "DRAWPIXEL" },
