  { handleWORDS, "words" },
  { handleABS, "abs" },
  { handleMIN, "min" },
  { handleMAX, "max" },
  { handleFact, "fact" },
  { handleMOD, "mod" },
  { handleAND, "and" },
  { handleOR, "or" },
  { handleXOR, "xor" },
  { handleNOT, "not" },
  { handleNEGATE, "negate" },
  { handleINVERT, "invert" },
  { handleSQR, "sqr" },
  { handleSQRT, "sqrt" },
  { handleSIN, "sin" },
  { handleCOS, "cos" },
  { handleTAN, "tan" },
  { handleASIN, "asin" },
  { handleACOS, "acos" },
  { handleATAN, "atan" },
  { handleSINH, "sinh" },
  { handleCOSH, "cosh" },
  { handleTANH, "tanh" },
  { handleLOG, "log" },
  { handleLOG10, "log10" },
  { handleROUND, "round" },
  { handleFLOOR, "floor" },
  { handleCEIL, "ceil" },
  { handleEXP, "exp" },
  { handleSETINT, "int"},
  { handleEMIT, "emit" },
  { handleKEY, "key" },
  { handleLINE, "line" },
  { handlePREPENDSTACKSTRING, "+str" },
  { handleAPPENDSTACKSTRING, "str+" },
  { handleLEFT, "leftstr" },
  { handleMID, "midstr" },
  { handleRIGHT, "rightstr" },
  { handleLEN, "lenstr" },
  { handleSUBSTR, "substr" },
  { handleLowercase, "lowerstr"},
  { handleUppercase, "upperstr"},
  { handleMULTSTR, "multstr"},
  { handleSTRIPSTR, "stripstr" },
  { handleLSTRIPSTR, "lstripstr" },
  { handleRSTRIPSTR, "rstripstr" },
  { handleINTSTR, "intstr"},
  { handleSTRINT, "strint"},
  { handleUPRINT, "u." },
  { handleDUP, "dup" },
  { handleDROP, "drop" },
  { handleSWAP, "swap" },
  { handleDEPTH, "depth" },
  { handleCLEAR, "clear" },
  { handleROT, "rot" },
  { handleROLL, "roll" },
  { handleOVER, "over" },
  { handleBASE, "base" },
  { handleBASE2, "bin" },
  { handleBASE10, "dec" },
  { handleBASE16, "hex" },
  { handleCR, "cr" },
  { showVars, ".v" },
  { handleBEGIN, "begin" },
  { handleUNTIL, "until" },
  { handleWHILE, "while" },
  { handleDO, "do" },
  { handleLOOP, "loop" },
  { handleI, "i" },
  { handleIprime, "i'" },
  { handleJ, "j" },
  { handleRput, ">r" },
  { handleRget, "r>" },
  { handleEXEC, "exec" },
  { handleLOAD, "load" },
  { putRandomByteOnStack, "random" },
  { putRandomUIntOnStack, "randomi" },
  { handleIF, "if" },
  { handleTHEN, "then" },
  { handleELSE, "else" },
  { handleEXIT, "exit" },
  { handleCELLS, "array"},
  { handleCELLSTORE, ">ix"},
  { handleCELLRETRIEVE, "ix>"},
  { handleCELLLENGTH, "len>"},
  { handleCELLAPPEND, "ix+"},
  { handleCELLPREPEND, "+ix"},
  { handleCELLLROT, "<rot"},
  { handleCELLRROT, "rot>"},
  { handleCELLLIST, "alist"},
